### PR TITLE
Fix deprecation warnings

### PR DESCRIPTION
**Pull request by ranjanan**

### CODE REVIEW

**Comment by ViralBShah** [comment]
@dcjones Can you give a few more people commit access? Or perhaps move the packages to an organization?

**Comment by dcjones** [comment]
I've added you an @ranjanan. Let me know if there are others I should add.

**Comment by ViralBShah** [comment]
Thanks @dcjones.

**Comment by ViralBShah** [comment]
Cc @tkelman

**Comment by tkelman** [comment]
@ranjanan https://github.com/dcjones/Loess.jl/blob/9643b2b27bf2ae83881ce3902009a9018401d719/REQUIRE#L2


EVERY TIME

**Comment by ranjanan** [comment]
Thanks for adding me @dcjones :)

**Pull request merged**
