### PR TITLE
Add a simple test, fix dep warnings, add TravisCI

### PR DESCRIPTION
**Pull request by IainNZ**
You'd need to turn on Travis yourself (and tag, naturally)

This cuts down on a fairly large number of dep warnings from compiling Gadfly.

(This package could possibly move to JuliaStats if you don't want to concern yourself with it too much, as well)

### CODE REVIEW

**Comment by dcjones** [comment]
Thanks!

**Comment by tkelman** [comment]
please turn travis on?

**Comment by dcjones** [comment]
Ok, done.

**Comment by tkelman** [comment]
Yay, thanks.

**Pull request merged**
